-- CLASS 테이블 컬럼 수정
ALTER TABLE CLASS
DROP COLUMN C_TNAME;
ALTER TABLE CLASS
ADD C_WRITER NUMBER;
ALTER TABLE CLASS
MODIFY C_WRITER VARCHAR2(20) NOT NULL;
ALTER TABLE CLASS
ADD FOREIGN KEY(C_WRITER) REFERENCES MEMBER_INFO (USER_ID);
-- FILE 테이블 컬럼 추가
ALTER TABLE "FILE"
ADD ORIGIN_NAME VARCHAR2(50)
ADD FILE_LEVEL NUMBER
ADD CHANGE_NAME VARCHAR2(50)
ADD STATUS VARCHAR2(5);
ALTER TABLE "FILE"
ADD CHECK (STATUS IN ('Y', 'N'));
ALTER TABLE "FILE"
ADD CHECK (FILE_LEVEL IN (1, 2));

-- MEMBER_INFO 테이블 성별 컬럼 추가
ALTER TABLE MEMBER_INFO ADD USER_GENDER VARCHAR(3);

-- SOCIALING_MEMBER 게시판번호, 참여자 참조값 추가
ALTER TABLE SOCIALING_MEMBER
ADD (FOREIGN KEY(NOTICE_NUM) REFERENCES SOCIALING(NOTICE_NUM)
   , FOREIGN KEY(USER_ID) REFERENCES MEMBER_INFO(USER_ID));
   
-- SOCIALING 테이블 모임시간 컬럼 삭제
ALTER TABLE SOCIALING
DROP COLUMN S_TIME;

-- NOTICE 테이블에 ncount 속성 추가 (조회수)
AlTER TABLE NOTICE
ADD NCOUNT NUMBER;
COMMIT;
COMMENT ON COLUMN NOTICE.NCOUNT IS '게시판조회수';

-- NOTICE 테이블에 ncount 속성 추가 (조회수)
AlTER TABLE NOTICE
ADD NCOUNT NUMBER;
COMMIT;
COMMENT ON COLUMN NOTICE.NCOUNT IS '게시판조회수';

-- MEMBER_INFO테이블 USER_PHON(휴대폰번호) 컬럼 NOT NULL로 변경 (계정찾기할 때 이름+휴대폰번호로 찾아야해서 변경합니다!)
ALTER TABLE MEMBER_INFO
MODIFY USER_PHONE NOT NULL;

-- SOCIALING 테이블 MIN_MEMBER (최소 참여인원) 컬럼 추가
ALTER TABLE SOCIALING
ADD MIN_MEMBER NUMBER DEFAULT 2 NOT NULL;
COMMENT ON COLUMN SOCIALING.MIN_MEMBER IS '최소참여인원';
COMMENT ON COLUMN SOCIALING.MAX_MEMBER IS '최대참여인원';

-- PROFILE 테이블 LIKE_SOCIALING (관심 소셜링) 컬럼 추가 (소셜링 NOTICE_NUM 구분자 이용해서 추가예정)
ALTER TABLE PROFILE
ADD LIKE_SOCIALING VARCHAR2(30);
COMMENT ON COLUMN PROFILE.LIKE_SOCIALING IS '관심 소셜링';

-- CLASS 테이블 시간 속성 + 코멘트 추가
ALTER TABLE CLASS
ADD C_TIME1 VARCHAR2(30);
ALTER TABLE CLASS
ADD C_TIME2 VARCHAR2(30);
COMMENT ON COLUMN CLASS.C_TIME1 IS '클래스 시간1';
COMMENT ON COLUMN CLASS.C_TIME2 IS '클래스 시간2';

-- CLASS 테이블 위치 NULL 허용으로 변경
ALTER TABLE CLASS
MODIFY C_LOCATION NULL;

--FILE이라는 이름이 이클립스에서 인식이 안돼서 TBL_FILE로 변경합니다. 변경 안되면 직접 해주셔도 돼요
ALTER TABLE "FILE" RENAME TO TBL_FILE;

--파일 경로 길이가 길어서 30->100으로 변경합니다. FILE먼저 바꾸고 해주세요
ALTER TABLE TBL_FILE
MODIFY (ROUTE VARCHAR2(100));

-- MEMBER_INFO 테이블 성별 컬럼 크기 변경 (위에 카카오 로그인 하기 전에 변경해주세용)
ALTER TABLE MEMBER_INFO MODIFY USER_GENDER VARCHAR(6);

-- CLASS_MEMBER테이블에 회원 수강 날짜 속성 추가
ALTER TABLE CLASS_MEMBER
ADD SELECT_DATE DATE NOT NULL;
COMMENT ON COLUMN CLASS_MEMBER.SELECT_DATE IS '선택 날짜';

-- CLASS_MEMBER테이블의 PAY_NUM 속성 삭제
ALTER TABLE CLASS_MEMBER
DROP COLUMN PAY_NUM;

--NOTICE 테이블에 카테고리 컬럼 크기가 작아서 변경합니다
ALTER TABLE NOTICE MODIFY NOTICE_TYPE VARCHAR(20);

-- WISHLIST 테이블에 WISH_NUM 컬럼 추가 (USER_ID가 PK로 되어있어서 중복 불가하기 때문에)
-- USER_ID PK 삭제
ALTER TABLE WISHLIST DROP CONSTRAINT PK_WISHLIST;

-- 시퀀스 생성
CREATE SEQUENCE WISH_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOMINVALUE;

-- 시퀀스를 컬럼으로 추가
AlTER TABLE WISHLIST
ADD WISH_NUM NUMBER NOT NULL;
COMMENT ON COLUMN WISHLIST.WISH_NUM IS '장바구니번호';

-- 시퀀스 컬럼에 PK 추가
ALTER TABLE WISHLIST ADD CONSTRAINT PK_WISHLIST_NUM PRIMARY KEY (WISH_NUM) ENABLE;

-- WISHLIST 테이블에 WISH_STATUS 컬럼 추가 (삭제여부현황 Y/N)
ALTER TABLE WISHLIST
ADD WISH_STATUS VARCHAR2(2) DEFAULT 'N' NOT NULL;
COMMENT ON COLUMN WISHLIST.WISH_STATUS IS '장바구니삭제(Y/N)';

-- CLASS 테이블 C_TYPE 삭제
ALTER TABLE CLASS
DROP COLUMN C_TYPE;

-- CLASS 테이블 E_DATE 삭제
ALTER TABLE CLASS
DROP COLUMN C_EDATE;

-- MEMBER_INFO 테이블에서 USER_ADDRESS 삭제 (필요없는 컬럼) / 깃허브에서 쿼리문 수정한 거 받으시고 진행해야 코드오류안나요!
ALTER TABLE MEMBER_INFO
DROP COLUMN USER_ADDRESS;

--코멘트 이름이 인식이 잘 안돼서 REPLY로 변경합니다
ALTER TABLE "COMMENT" RENAME TO REPLY;

--REPLY 테이블에 댓글 작성자, 댓글 수정 날짜, 댓글 삭제 여부 추가
ALTER TABLE REPLY
ADD RWRITER VARCHAR2(20) NOT NULL;
COMMENT ON COLUMN REPLY.RWRITER IS "댓글작성자";
ALTER TABLE REPLY
ADD REPLY_MODIFYDATE DATE;
ALTER TABLE REPLY
ADD REPLY_STATUS VARCHAR2(2) NOT NULL;
COMMENT ON COLUMN REPLY.REPLY_STATUS IS "댓글삭제여부";
--기존의 COMMENT로 작성된 컬럼명 수정
ALTER TABLE REPLY
RENAME COLUMN COMMENT_NUM TO REPLY_NUM;
ALTER TABLE REPLY
RENAME COLUMN COMMENT_CONTENT TO REPLY_CONTENT;
ALTER TABLE REPLY
RENAME COLUMN CONMENT_DATE TO REPLY_DATE;
ALTER TABLE REPLY
RENAME COLUMN COMMENT_SELF_NUM TO REPLY_SELF_NUM;
--댓글 내용 VARCHAR2(20)에서 100으로 변경합니다
ALTER TABLE REPLY MODIFY REPLY_CONTENT VARCHAR2(100);

-- NOTICE 테이블 NOTICE_CONTENT 컬럼 크기 변경 (300 -> 1000)
ALTER TABLE NOTICE
MODIFY NOTICE_CONTENT VARCHAR2(1000);

-- CLASS 테이블 C_SDATE 타입 변경
ALTER TABLE CLASS
DROP COLUMN C_SDATE;
ALTER TABLE CLASS
ADD C_SDATE varchar2(30);
COMMENT ON COLUMN CLASS.C_SDATE IS '시작 날짜';
-- CLASS 테이블 C_LOCATION 크기 변경
ALTER TABLE CLASS
MODIFY C_LOCATION VARCHAR2(100);
-- NOTICE 테이블 C_TUTOR 컬럼 크기 변경 (100 -> 1000)
ALTER TABLE CLASS
MODIFY C_TUTOR VARCHAR2(1000);
-- CLASS 테이블 C_SDATE 이름 변경 (원데이랑 VOD 날짜 입력 방식이 달라서 구분을 위해)
ALTER TABLE CLASS
RENAME COLUMN C_SDATE TO V_DATE;
-- CLASS 테이블 원데이 클래스 날짜 속성 추가
ALTER TABLE CLASS
ADD O_DATE1 DATE;
ALTER TABLE CLASS
ADD O_DATE2 DATE;
COMMENT ON COLUMN CLASS.V_DATE IS 'VOD 날짜';
COMMENT ON COLUMN CLASS.O_DATE1 IS '원데이 날짜';
COMMENT ON COLUMN CLASS.O_DATE2 IS '원데이 날짜';

-- SOCIALING 테이블 S_PLACE 컬럼 크기 변경
ALTER TABLE SOCIALING
MODIFY S_PLACE VARCHAR2(100);

-- CLASS 테이블 C_STITLE 삭제
ALTER TABLE CLASS
DROP COLUMN C_STITLE;

-- NOTICE 테이블 NOTICE_TITLE 컬럼 크기 변경
ALTER TABLE NOTICE
MODIFY NOTICE_TITLE VARCHAR2(60);

-- SOCIALING 테이블 S_TIME 컬럼 추가
ALTER TABLE SOCIALING
ADD S_TIME VARCHAR2(30);
COMMENT ON COLUMN SOCIALING.S_TIME IS '모임시간';

-- TBL_FILE테이블 STATUS NOT NULL로 변경
ALTER TABLE TBL_FILE
MODIFY STATUS NOT NULL;

--마이 피드 프로필 사진 관리 때문에 파일 게시판 생성했습니다
CREATE TABLE PROFILE_FILE (
	FILE_NUM	NUMBER	NOT NULL ,
	ROUTE	VARCHAR2(30)	NOT NULL,
	USER_ID	VARCHAR2(30)	NOT NULL,
	ORIGIN_NAME	VARCHAR2(30)	NOT NULL,
    CHANGE_NAME	VARCHAR2(30)	NOT NULL,
	STATUS	VARCHAR2(3)	DEFAULT 'N' NOT NULL
);
ALTER TABLE PROFILE_FILE ADD CONSTRAINT PK_PROFILE_FILE PRIMARY KEY (
	FILE_NUM
);

-- WISHLIST 테이블에 SELECT_DATE 컬럼 추가
ALTER TABLE WISHLIST
ADD SELECT_DATE DATE;
COMMENT ON COLUMN WISHLIST.SELECT_DATE IS '원데이선택날짜';

--PROFILE FILE 테이블 시퀀스 생성
ALTER TABLE PROFILE_FILE
RENAME COLUMN FILE_NUM TO FILE_NO;	
    CREATE SEQUENCE SEQ_FILE_NO;
    
-- 게시판번호 시퀀스 생성
CREATE SEQUENCE SEQ_BNUM
NOCYCLE
NOCACHE;
-- 첨부파일 시퀀스 생성
CREATE SEQUENCE SEQ_FNUM
NOCYCLE
NOCACHE;
-- NOTICE 테이블에 SOCIALING 가데이터 10행 삽입
BEGIN
    FOR I IN 1..10
    LOOP
        INSERT INTO NOTICE
        VALUES(SEQ_BNUM.NEXTVAL, '글 제목' || I, '글 내용' || I, DEFAULT, DEFAULT, '소셜링', 'semi@gmail.com', SYSDATE, NULL, 0);
        INSERT INTO SOCIALING
        VALUES(SEQ_BNUM.CURRVAL, '경기도 안양시 동안구 시민대로 190|범계역 2번출구', SYSDATE, DEFAULT, DEFAULT, DEFAULT, '16:30');
        INSERT INTO TBL_FILE
        VALUES(SEQ_FNUM.NEXTVAL, SEQ_BNUM.CURRVAL, '/resources/uploadFiles/', 'flower1.PNG', 1, 'change2.png', 'Y');
    END LOOP;
END;
/

COMMIT;