CREATE TABLE "MEMBER_INFO" (
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "USER_NAME"   VARCHAR2(20)      NOT NULL,
   "USER_PHONE"   VARCHAR2(20)      NULL,
   "USER_PWD"   VARCHAR2(20)      NOT NULL,
   "USER_ADDRESS"   VARCHAR2(30)      NULL,
   "JOIN_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "STATUS"   VARCHAR   DEFAULT 'Y'   NOT NULL,
   "USER_GRADE"   VARCHAR2(10)   DEFAULT '회원'   NOT NULL
);

COMMENT ON COLUMN "MEMBER_INFO"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "MEMBER_INFO"."USER_NAME" IS '회원이름';

COMMENT ON COLUMN "MEMBER_INFO"."USER_PHONE" IS '휴대폰번호';

COMMENT ON COLUMN "MEMBER_INFO"."USER_PWD" IS '비밀번호';

COMMENT ON COLUMN "MEMBER_INFO"."USER_ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER_INFO"."JOIN_DATE" IS '가입일';

COMMENT ON COLUMN "MEMBER_INFO"."STATUS" IS '탈퇴여부(Y/N)';

COMMENT ON COLUMN "MEMBER_INFO"."USER_GRADE" IS '회원등급';

CREATE TABLE "NOTICE" (
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "NOTICE_TITLE"   VARCHAR2(50)      NOT NULL,
   "NOTICE_CONTENT"   VARCHAR2(300)      NOT NULL,
   "NOTICE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "NOTICE_STATUS"   VARCHAR   DEFAULT 'N'   NOT NULL,
   "NOTICE_TYPE"   VARCHAR2(10)      NOT NULL,
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "MODIFY_DATE"   DATE      NOT NULL,
   "NOTICE_SELF_NUM"   VARCHAR2(20)      NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NUM" IS '게시판번호';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '게시판제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '게시판내용';

COMMENT ON COLUMN "NOTICE"."NOTICE_DATE" IS '작성일';

COMMENT ON COLUMN "NOTICE"."NOTICE_STATUS" IS '게시판삭제(Y/N)';

COMMENT ON COLUMN "NOTICE"."NOTICE_TYPE" IS '게시판종류';

COMMENT ON COLUMN "NOTICE"."USER_ID" IS '작성자ID';

COMMENT ON COLUMN "NOTICE"."MODIFY_DATE" IS '게시판수정일';

COMMENT ON COLUMN "NOTICE"."NOTICE_SELF_NUM" IS '게시판셀프참조번호';

CREATE TABLE "COMMENT" (
   "COMMENT_NUM"   NUMBER      NOT NULL,
   "COMMENT_CONTENT"   VARCHAR2(50)      NOT NULL,
   "CONMENT_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "COMMENT_SELF_NUM"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "COMMENT"."COMMENT_NUM" IS '댓글번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "COMMENT"."CONMENT_DATE" IS '댓글작성일시';

COMMENT ON COLUMN "COMMENT"."NOTICE_NUM" IS '게시판번호';

COMMENT ON COLUMN "COMMENT"."COMMENT_SELF_NUM" IS '대댓글';

CREATE TABLE "REFUND" (
   "PAY_NUM"   NUMBER      NOT NULL,
   "REFUND_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "REFUND_ACCOUNT"   VARCHAR2(30)      NOT NULL,
   "BANK"   VARCHAR2(20)      NOT NULL,
   "ACCOUNT_HOLDER"   VARCHAR2(20)      NOT NULL,
   "REFUND_PROCESS"   VARCHAR2(30)      NOT NULL
);

COMMENT ON COLUMN "REFUND"."PAY_NUM" IS '주문번호';

COMMENT ON COLUMN "REFUND"."REFUND_DATE" IS '환불날짜';

COMMENT ON COLUMN "REFUND"."REFUND_ACCOUNT" IS '환불계좌';

COMMENT ON COLUMN "REFUND"."BANK" IS '은행종류';

COMMENT ON COLUMN "REFUND"."ACCOUNT_HOLDER" IS '환불받는사람';

COMMENT ON COLUMN "REFUND"."REFUND_PROCESS" IS '환불처리현황';

CREATE TABLE "PROFILE" (
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "PROFILE"   VARCHAR2(50)   DEFAULT 기본사진   NOT NULL,
   "INTRODUCTION"   VARCHAR2(100)      NOT NULL,
   "FEED_STATUS"   VARCHAR   DEFAULT Y   NULL,
   "SOCIALING"   VARCHAR   DEFAULT Y   NULL,
   "SNS"   VARCHAR(20)      NULL,
   "INTEREST"   VARCHAR(30)      NULL
);

COMMENT ON COLUMN "PROFILE"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "PROFILE"."PROFILE" IS '회원프로필사진';

COMMENT ON COLUMN "PROFILE"."INTRODUCTION" IS '자기소개';

COMMENT ON COLUMN "PROFILE"."FEED_STATUS" IS 'Y/N';

COMMENT ON COLUMN "PROFILE"."SOCIALING" IS 'Y/N';

COMMENT ON COLUMN "PROFILE"."SNS" IS 'SNS';

COMMENT ON COLUMN "PROFILE"."INTEREST" IS '관심사';

CREATE TABLE "FOLLOW" (
   "FOLLOW_NUM"   NUMBER      NOT NULL,
   "FOLLOWING"   VARCHAR2(30)      NULL,
   "FOLLOWER"   VARCHAR2(30)      NULL
);

COMMENT ON COLUMN "FOLLOW"."FOLLOW_NUM" IS '팔로잉, 팔로워번호';

COMMENT ON COLUMN "FOLLOW"."FOLLOWING" IS '팔로우 한 사람';

COMMENT ON COLUMN "FOLLOW"."FOLLOWER" IS '팔로우 된 사람';

CREATE TABLE "SOCIALING" (
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "S_PLACE"   VARCHAR2(50)      NOT NULL,
   "S_DATE"   DATE      NOT NULL,
   "S_TIME"   DATE      NOT NULL,
   "S_TYPE"   VARCHAR2(10)   DEFAULT 'OFF'   NOT NULL,
   "MAX_MEMBER"   NUMBER   DEFAULT 2   NOT NULL
);

COMMENT ON COLUMN "SOCIALING"."NOTICE_NUM" IS '게시판번호';

COMMENT ON COLUMN "SOCIALING"."S_PLACE" IS '모임장소';

COMMENT ON COLUMN "SOCIALING"."S_DATE" IS '모임날짜';

COMMENT ON COLUMN "SOCIALING"."S_TIME" IS '모임시간';

COMMENT ON COLUMN "SOCIALING"."S_TYPE" IS '온오프라인여부(ON/OFF)';

COMMENT ON COLUMN "SOCIALING"."MAX_MEMBER" IS '참여가능인원';

CREATE TABLE "SOCIALING_MEMBER" (
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "S_STATUS"   VARCHAR   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "SOCIALING_MEMBER"."NOTICE_NUM" IS '게시판번호';

COMMENT ON COLUMN "SOCIALING_MEMBER"."USER_ID" IS '참여회원ID';

COMMENT ON COLUMN "SOCIALING_MEMBER"."S_STATUS" IS '참여완료여부(Y/N)';

CREATE TABLE "WISHLIST" (
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "NOTICE_NUM"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "WISHLIST"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "WISHLIST"."NOTICE_NUM" IS '게시판번호';

CREATE TABLE "PAYMENT" (
   "PAY_NUM"   NUMBER      NOT NULL,
   "PAY_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "PAY_OPTION"   VARCHAR2(10)      NOT NULL,
   "PAY_PHONE"   VARCHAR2(10)      NULL,
   "PAY_EMAIL"   VARCHAR2(20)      NULL,
   "PAY_CANCLE"   VARCHAR   DEFAULT 'N'   NOT NULL,
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "NOTICE_NUM"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."PAY_NUM" IS '주문번호';

COMMENT ON COLUMN "PAYMENT"."PAY_DATE" IS '결제일자';

COMMENT ON COLUMN "PAYMENT"."PAY_OPTION" IS '결제수단';

COMMENT ON COLUMN "PAYMENT"."PAY_PHONE" IS '주문자연락처';

COMMENT ON COLUMN "PAYMENT"."PAY_EMAIL" IS '주문자이메일';

COMMENT ON COLUMN "PAYMENT"."PAY_CANCLE" IS '취소환불현황(Y/N)';

COMMENT ON COLUMN "PAYMENT"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "PAYMENT"."NOTICE_NUM" IS '게시판번호';

CREATE TABLE "CLASS_MEMBER" (
   "C_MEM_ID"   VARCHAR2(30)      NOT NULL,
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "PAY_NUM"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "CLASS_MEMBER"."PAY_NUM" IS '주문번호';

CREATE TABLE "CLASS_QA" (
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "C_QUESTION"   VARCHAR2(100)      NULL,
   "C_ANSWER"   VARCHAR2(100)      NULL
);

COMMENT ON COLUMN "CLASS_QA"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "CLASS_QA"."NOTICE_NUM" IS '게시판 번호';

COMMENT ON COLUMN "CLASS_QA"."C_QUESTION" IS '문의내용';

COMMENT ON COLUMN "CLASS_QA"."C_ANSWER" IS '답변내용';

CREATE TABLE "REPORT" (
   "REPORT_NUM"   NUMBER      NOT NULL,
   "REPORT_REASON"   VARCHAR2(30)      NOT NULL,
   "COMMENT_NUM"   NUMBER      NULL,
   "NOTICE_NUM"   NUMBER      NULL,
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "REPORT_DATE"   DATE   DEFAULT SYSDATE   NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NUM" IS '신고번호';

COMMENT ON COLUMN "REPORT"."REPORT_REASON" IS '신고사유';

COMMENT ON COLUMN "REPORT"."COMMENT_NUM" IS '댓글번호';

COMMENT ON COLUMN "REPORT"."NOTICE_NUM" IS '게시판번호';

COMMENT ON COLUMN "REPORT"."USER_ID" IS '신고한회원ID';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고일';

CREATE TABLE "CLASS" (
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "C_STITLE"   VARCHAR2(30)      NOT NULL,
   "C_TNAME"   VARCHAR2(15)      NOT NULL,
   "C_TAG1"   VARCHAR2(20)      NOT NULL,
   "C_TAG2"   VARCHAR2(20)      NOT NULL,
   "C_PRICE"   NUMBER      NOT NULL,
   "C_TYPE"   VARCHAR2(15)      NOT NULL,
   "C_CATEGORY"   VARCHAR2(20)      NOT NULL,
   "C_SDATE"   DATE      NOT NULL,
   "C_EDATE"   DATE      NOT NULL,
   "C_LOCATION"   VARCHAR2(50)      NOT NULL,
   "C_TUTOR"   VARCHAR2(100)      NOT NULL
);

COMMENT ON COLUMN "CLASS"."NOTICE_NUM" IS '게시판 번호';

COMMENT ON COLUMN "CLASS"."C_STITLE" IS '서브제목';

COMMENT ON COLUMN "CLASS"."C_TNAME" IS '강사이름';

COMMENT ON COLUMN "CLASS"."C_TAG1" IS '태그1';

COMMENT ON COLUMN "CLASS"."C_TAG2" IS '태그2';

COMMENT ON COLUMN "CLASS"."C_PRICE" IS '클래스 가격';

COMMENT ON COLUMN "CLASS"."C_TYPE" IS '온라인/오프라인';

COMMENT ON COLUMN "CLASS"."C_CATEGORY" IS '원데이/vod';

COMMENT ON COLUMN "CLASS"."C_SDATE" IS '수강 시작일';

COMMENT ON COLUMN "CLASS"."C_EDATE" IS '수강 종료일';

COMMENT ON COLUMN "CLASS"."C_LOCATION" IS '위치';

COMMENT ON COLUMN "CLASS"."C_TUTOR" IS '강사 소개';

CREATE TABLE "FILE" (
   "FILE_NUM"   NUMBER      NOT NULL,
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "ROUTE"   VARCHAR2(30)      NOT NULL
);

COMMENT ON COLUMN "FILE"."FILE_NUM" IS '첨부파일번호';

COMMENT ON COLUMN "FILE"."NOTICE_NUM" IS '게시판번호';

COMMENT ON COLUMN "FILE"."ROUTE" IS '첨부파일경로';

ALTER TABLE "MEMBER_INFO" ADD CONSTRAINT "PK_MEMBER_INFO" PRIMARY KEY (
   "USER_ID"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
   "NOTICE_NUM"
);

ALTER TABLE "COMMENT" ADD CONSTRAINT "PK_COMMENT" PRIMARY KEY (
   "COMMENT_NUM"
);

ALTER TABLE "REFUND" ADD CONSTRAINT "PK_REFUND" PRIMARY KEY (
   "PAY_NUM"
);

ALTER TABLE "PROFILE" ADD CONSTRAINT "PK_PROFILE" PRIMARY KEY (
   "USER_ID"
);

ALTER TABLE "FOLLOW" ADD CONSTRAINT "PK_FOLLOW" PRIMARY KEY (
   "FOLLOW_NUM"
);

ALTER TABLE "SOCIALING" ADD CONSTRAINT "PK_SOCIALING" PRIMARY KEY (
   "NOTICE_NUM"
);

ALTER TABLE "SOCIALING_MEMBER" ADD CONSTRAINT "PK_SOCIALING_MEMBER" PRIMARY KEY (
   "NOTICE_NUM",
   "USER_ID"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
   "USER_ID",
   "NOTICE_NUM"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
   "PAY_NUM"
);

ALTER TABLE "CLASS_MEMBER" ADD CONSTRAINT "PK_CLASS_MEMBER" PRIMARY KEY (
   "C_MEM_ID",
   "NOTICE_NUM"
);

ALTER TABLE "CLASS_QA" ADD CONSTRAINT "PK_CLASS_QA" PRIMARY KEY (
   "USER_ID",
   "NOTICE_NUM"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
   "REPORT_NUM"
);

ALTER TABLE "CLASS" ADD CONSTRAINT "PK_CLASS" PRIMARY KEY (
   "NOTICE_NUM"
);

ALTER TABLE "FILE" ADD CONSTRAINT "PK_FILE" PRIMARY KEY (
   "FILE_NUM"
);

ALTER TABLE "REFUND" ADD CONSTRAINT "FK_PAYMENT_TO_REFUND_1" FOREIGN KEY (
   "PAY_NUM"
)
REFERENCES "PAYMENT" (
   "PAY_NUM"
);

ALTER TABLE "PROFILE" ADD CONSTRAINT "FK_MEMBER_INFO_TO_PROFILE_1" FOREIGN KEY (
   "USER_ID"
)
REFERENCES "MEMBER_INFO" (
   "USER_ID"
);

ALTER TABLE "SOCIALING" ADD CONSTRAINT "FK_NOTICE_TO_SOCIALING_1" FOREIGN KEY (
   "NOTICE_NUM"
)
REFERENCES "NOTICE" (
   "NOTICE_NUM"
);

ALTER TABLE "SOCIALING_MEMBER" ADD CONSTRAINT "FK_SOCIALING_TO_SOCIALING_MEMBER_1" FOREIGN KEY (
   "NOTICE_NUM"
)
REFERENCES "SOCIALING" (
   "NOTICE_NUM"
);

ALTER TABLE "SOCIALING_MEMBER" ADD CONSTRAINT "FK_MEMBER_INFO_TO_SOCIALING_MEMBER_1" FOREIGN KEY (
   "USER_ID"
)
REFERENCES "MEMBER_INFO" (
   "USER_ID"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_MEMBER_INFO_TO_WISHLIST_1" FOREIGN KEY (
   "USER_ID"
)
REFERENCES "MEMBER_INFO" (
   "USER_ID"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_CLASS_TO_WISHLIST_1" FOREIGN KEY (
   "NOTICE_NUM"
)
REFERENCES "CLASS" (
   "NOTICE_NUM"
);

ALTER TABLE "CLASS_MEMBER" ADD CONSTRAINT "FK_MEMBER_INFO_TO_CLASS_MEMBER_1" FOREIGN KEY (
   "C_MEM_ID"
)
REFERENCES "MEMBER_INFO" (
   "USER_ID"
);

ALTER TABLE "CLASS_MEMBER" ADD CONSTRAINT "FK_CLASS_TO_CLASS_MEMBER_1" FOREIGN KEY (
   "NOTICE_NUM"
)
REFERENCES "CLASS" (
   "NOTICE_NUM"
);

ALTER TABLE "CLASS_QA" ADD CONSTRAINT "FK_MEMBER_INFO_TO_CLASS_QA_1" FOREIGN KEY (
   "USER_ID"
)
REFERENCES "MEMBER_INFO" (
   "USER_ID"
);

ALTER TABLE "CLASS_QA" ADD CONSTRAINT "FK_CLASS_TO_CLASS_QA_1" FOREIGN KEY (
   "NOTICE_NUM"
)
REFERENCES "CLASS" (
   "NOTICE_NUM"
);

ALTER TABLE "CLASS" ADD CONSTRAINT "FK_NOTICE_TO_CLASS_1" FOREIGN KEY (
   "NOTICE_NUM"
)
REFERENCES "NOTICE" (
   "NOTICE_NUM"
);

CREATE TABLE MEMBER_INFO (
   USER_ID   VARCHAR2(30)      NOT NULL,
   USER_NAME   VARCHAR2(20)      NOT NULL,
   USER_PHONE   VARCHAR2(20)      NULL,
   USER_PWD   VARCHAR2(20)      NOT NULL,
   USER_ADDRESS   VARCHAR2(30)      NULL,
   JOIN_DATE   DATE   DEFAULT SYSDATE   NOT NULL,
   STATUS   VARCHAR2(5)   DEFAULT 'Y'   NOT NULL,
   USER_GRADE   VARCHAR2(10)   DEFAULT '회원'   NOT NULL
);

COMMENT ON COLUMN "MEMBER_INFO"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "MEMBER_INFO"."USER_NAME" IS '회원이름';

COMMENT ON COLUMN "MEMBER_INFO"."USER_PHONE" IS '휴대폰번호';

COMMENT ON COLUMN "MEMBER_INFO"."USER_PWD" IS '비밀번호';

COMMENT ON COLUMN "MEMBER_INFO"."USER_ADDRESS" IS '주소';

COMMENT ON COLUMN "MEMBER_INFO"."JOIN_DATE" IS '가입일';

COMMENT ON COLUMN "MEMBER_INFO"."STATUS" IS '탈퇴여부(Y/N)';

COMMENT ON COLUMN "MEMBER_INFO"."USER_GRADE" IS '회원등급';

CREATE TABLE "NOTICE" (
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "NOTICE_TITLE"   VARCHAR2(50)      NOT NULL,
   "NOTICE_CONTENT"   VARCHAR2(300)      NOT NULL,
   "NOTICE_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "NOTICE_STATUS"   VARCHAR2(5)   DEFAULT 'N'   NOT NULL,
   "NOTICE_TYPE"   VARCHAR2(10)      NOT NULL,
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "MODIFY_DATE"   DATE      NOT NULL,
   "NOTICE_SELF_NUM"   VARCHAR2(20)      NOT NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NUM" IS '게시판번호';

COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS '게시판제목';

COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS '게시판내용';

COMMENT ON COLUMN "NOTICE"."NOTICE_DATE" IS '작성일';

COMMENT ON COLUMN "NOTICE"."NOTICE_STATUS" IS '게시판삭제(Y/N)';

COMMENT ON COLUMN "NOTICE"."NOTICE_TYPE" IS '게시판종류';

COMMENT ON COLUMN "NOTICE"."USER_ID" IS '작성자ID';

COMMENT ON COLUMN "NOTICE"."MODIFY_DATE" IS '게시판수정일';

COMMENT ON COLUMN "NOTICE"."NOTICE_SELF_NUM" IS '게시판셀프참조번호';


CREATE TABLE "PROFILE" (
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "PROFILE"   VARCHAR2(50)   DEFAULT 기본사진   NOT NULL,
   "INTRODUCTION"   VARCHAR2(100)      NOT NULL,
   "FEED_STATUS"   VARCHAR2(5)   DEFAULT Y   NULL,
   "SOCIALING"   VARCHAR2(5)   DEFAULT Y   NULL,
   "SNS"   VARCHAR(20)      NULL,
   "INTEREST"   VARCHAR(30)      NULL
);

COMMENT ON COLUMN "PROFILE"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "PROFILE"."PROFILE" IS '회원프로필사진';

COMMENT ON COLUMN "PROFILE"."INTRODUCTION" IS '자기소개';

COMMENT ON COLUMN "PROFILE"."FEED_STATUS" IS 'Y/N';

COMMENT ON COLUMN "PROFILE"."SOCIALING" IS 'Y/N';

COMMENT ON COLUMN "PROFILE"."SNS" IS 'SNS';

COMMENT ON COLUMN "PROFILE"."INTEREST" IS '관심사';


CREATE TABLE "SOCIALING_MEMBER" (
   "NOTICE_NUM"   NUMBER      NOT NULL,
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "S_STATUS"   VARCHAR2(5)   DEFAULT 'N'   NOT NULL
);

COMMENT ON COLUMN "SOCIALING_MEMBER"."NOTICE_NUM" IS '게시판번호';

COMMENT ON COLUMN "SOCIALING_MEMBER"."USER_ID" IS '참여회원ID';

COMMENT ON COLUMN "SOCIALING_MEMBER"."S_STATUS" IS '참여완료여부(Y/N)';


CREATE TABLE "PAYMENT" (
   "PAY_NUM"   NUMBER      NOT NULL,
   "PAY_DATE"   DATE   DEFAULT SYSDATE   NOT NULL,
   "PAY_OPTION"   VARCHAR2(10)      NOT NULL,
   "PAY_PHONE"   VARCHAR2(10)      NULL,
   "PAY_EMAIL"   VARCHAR2(20)      NULL,
   "PAY_CANCLE"   VARCHAR2(5)   DEFAULT 'N'   NOT NULL,
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "NOTICE_NUM NULL"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."PAY_NUM" IS '주문번호';

COMMENT ON COLUMN "PAYMENT"."PAY_DATE" IS '결제일자';

COMMENT ON COLUMN "PAYMENT"."PAY_OPTION" IS '결제수단';

COMMENT ON COLUMN "PAYMENT"."PAY_PHONE" IS '주문자연락처';

COMMENT ON COLUMN "PAYMENT"."PAY_EMAIL" IS '주문자이메일';

COMMENT ON COLUMN "PAYMENT"."PAY_CANCLE" IS '취소환불현황(Y/N)';

COMMENT ON COLUMN "PAYMENT"."USER_ID" IS '회원ID';

COMMENT ON COLUMN "PAYMENT"."NOTICE_NUM" IS '게시판번호';

COMMENT ON COLUMN "CLASS_MEMBER"."PAY_NUM" IS '주문번호';

CREATE TABLE "PROFILE" (
   "USER_ID"   VARCHAR2(30)      NOT NULL,
   "PROFILE"   VARCHAR2(50)   DEFAULT '기본사진'   NOT NULL,
   "INTRODUCTION"   VARCHAR2(100)      NOT NULL,
   "FEED_STATUS"   VARCHAR2(5)   DEFAULT 'Y'   NULL,
   "SOCIALING"   VARCHAR2(5)   DEFAULT 'Y'   NULL,
   "SNS"   VARCHAR(20)      NULL,
   "INTEREST"   VARCHAR(30)      NULL
);
